- name: Deploy to Tomcat
  hosts: web
  become: yes
  tasks:
    - name: Copy WAR file to Tomcat
      copy:
        src: /var/snap/jenkins/5042/workspace/AnsibleApp01/target/AnsibleApp01.war
        dest: "/opt/tomcat/webapps/AnsibleApp01.war"
        remote_src: no

    - name: Restart Tomcat
      shell: |
        /opt/tomcat/bin/shutdown.sh || true
        sleep 5
        /opt/tomcat/bin/startup.sh
